services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./api/app:/app/app
      - ./models:/app/models
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

    depends_on:
      - postgres

  postgres:
    image: postgres:15
    # Set up the default database, user, and password
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Declare named volumes to be used for persistent storage
volumes:
  postgres_data: {}