services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./api/app:/app/app
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - cross-guild-network

  discord:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./discord-bot:/app/
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - cross-guild-network

  postgres:
    image: postgres:15
    # Set up the default database, user, and password
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cross-guild-network

# Declare named volumes to be used for persistent storage
volumes:
  postgres_data: {}

networks:
  cross-guild-network:
    driver: bridge
